// Importing DXF file, test.
//linear_extrude(height = 10, center = true, convexity = 10, twist=0)
//import("../../rpi_MECH_3b_1p2.dxf");
// Below: generated by Drga & Drop in the editor
// import("/Users/olediour/repos/3DPrinting/rpi_MECH_4b_4p0-with_mounting.dxf");
// import("/Users/olediour/repos/3DPrinting/rpi_MECH_3b_1p2.dxf");
translate([-45, -30, 0]) {
	linear_extrude(height = 1, center = true, convexity = 10) {
		import("../../rpi_MECH_4b_4p0-with_mounting.dxf");
	}
}
